spring:
  datasource:
    url: jdbc:mysql://8.140.224.10:3306/farmstay_db
    username: root
    password: 123456
sa-token:
  token-name: farmstay-token
  timeout: 1800
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
logging:
  level:
    com.gxy: debug

